ARTICLES = {
    "British couple on new hunger strike in Iranian jail, family say": "https://www.bbc.com/news/articles/c8e890y14r5o",
    "Iranian journalist describes London stabbing by 'men working for Iran'": "https://www.bbc.com/news/articles/ckgpmdepz19o",
    "Trump says he called off new Iran attack at request of Gulf states": "https://www.bbc.com/news/articles/c7079e55zjro",
    "Iranian journalist stabbed in UK by men working for Iran, court told": "https://www.bbc.com/news/articles/c3d205nxee8o",
    "'This may be the last time you hear my voice': Political executions surge in Iran since start of war": "https://www.bbc.com/news/articles/cn8p392nl7yo",
    "Trump says 20-year nuclear programme suspension by Iran would be enough": "https://www.bbc.com/news/articles/cgkpnnen5dzo",
    "'Floating armoury' ship reportedly seized by Iran": "https://www.bbc.com/news/articles/cx219xwxg9no",
    "Netanyahu says he 'secretly visited' UAE during war with Iran": "https://www.bbc.com/news/articles/czj2mnwv1ryo",
    "Contact with pair held in Iran cut off, family says": "https://www.bbc.com/news/articles/cewpydlkgq7o",
    "UK promises jets, drones and warship for Strait of Hormuz defence mission": "https://www.bbc.com/news/articles/c5y909grldqo",
    "Trump says Iran ceasefire is on 'massive life support'": "https://www.bbc.com/news/articles/cvgznxn18zgo",
    "Ailing Iranian Nobel laureate given bail and hospital transfer": "https://www.bbc.com/news/articles/c1j257w87neo",
    "Iran war leads to spike in saffron price": "https://www.bbc.com/news/articles/c9v3e4dz97yo",
    "Trump calls Iran response to US proposal to end war 'totally unacceptable'": "https://www.bbc.com/news/articles/clypgz9e5pmo",
    "Iranian activist tells BBC how fear of war restarting intensifies trauma of repression": "https://www.bbc.com/news/articles/c1m2ee3jxvro",
    "Rising fuel costs hit London's air ambulance": "https://www.bbc.com/news/articles/cx21ge89ldvo",
    "Iran accuses US of 'reckless military adventure'": "https://www.bbc.com/news/articles/c99lpn9ze8ro",
    "Trump says US-Iran ceasefire still in place after exchange of fire in Strait of Hormuz": "https://www.bbc.com/news/articles/c626zyywxjno",
    "Air ambulances in South hit by rising fuel costs": "https://www.bbc.com/news/articles/c5ye07k7ep1o",
    "Iran considering US proposal as Trump says war will be 'over quickly'": "https://www.bbc.com/news/articles/cj0pq2q8221o",
    "Trump's hopes for an Iran peace deal come with caveats": "https://www.bbc.com/news/articles/cvgzp74rvj5o",
    "Trump pauses Hormuz plan 50 hours after he announced it - what happened?": "https://www.bbc.com/news/articles/cd6p5q2dx1po",
    "China calls for Strait to be reopened 'as soon as possible' in Iran talks": "https://www.bbc.com/news/articles/c0m21mndm71o",
    "What is Trump's 'Project Freedom' in the Strait of Hormuz?": "https://www.bbc.com/news/articles/c4g437depzpo",
    "Trump says US to pause operation to guide vessels through Strait of Hormuz": "https://www.bbc.com/news/articles/clypekl71gdo",
    "Bowen: Strait of Hormuz standoff raises risk of sliding back into all-out war": "https://www.bbc.com/news/articles/cgrpnq00j5vo",
    "US strikes Iranian fast boats as Iran attacks UAE oil facility": "https://www.bbc.com/news/articles/cjwp432d0v5o",
    "US denies Iranian report warship was struck by missiles": "https://www.bbc.com/news/articles/c775jevkyv2o",
    "Some Iranians fear the regime is now more entrenched - and ready for revenge": "https://www.bbc.com/news/articles/clyp6xxyvzyo",
    "Iran says US has responded to its latest peace proposal": "https://www.bbc.com/news/articles/cn0px2x53k2o",
    "Concern for jailed Iranian Nobel laureate as brother fears she is dying": "https://www.bbc.com/news/articles/c362pd8epw9o",
    "The clandestine network smuggling Starlink tech into Iran to beat internet blackout": "https://www.bbc.com/news/articles/cvgzk91leweo",
    "US threatens shipping firms with sanctions if they pay Iran tolls": "https://www.bbc.com/news/articles/c3v2l2qq9qlo",
    "Trump claims other presidents flouted war powers law. It's a mixed record": "https://www.bbc.com/news/articles/c794zlx5lx8o",
    "Trump repeats that he is 'not happy' with Iran as deadline to seek approval for war looms": "https://www.bbc.com/news/articles/cvgz7l5v03po",
    "British couple jailed in Iran: 'We're likely to be here for a long time'": "https://www.bbc.com/news/articles/c202pl60kv9o",
    "Trump says US studying troop cuts in Germany, as spat with Merz intensifies": "https://www.bbc.com/news/articles/clyplg23l30o",
    "Why and how is US blockading Iranian ports in Strait of Hormuz?": "https://www.bbc.com/news/articles/c5yv6xr6me3o",
    "Oil price rises above $120 after reports of 'extended' Iran blockade": "https://www.bbc.com/news/articles/cj4pxr0gr02o",
    "Former US officials criticise Pentagon silence on deadly Iran school attack": "https://www.bbc.com/news/articles/cwy2482pn0lo",
    "A faraway conflict threatens livelihoods in India's glass hub": "https://www.bbc.com/news/articles/ce8pdv86359o",
    "Russian superyacht sails through Strait of Hormuz despite blockade": "https://www.bbc.com/news/articles/cm2pn8zdxdjo",
    "Homecare workers warn fuel costs are unsustainable": "https://www.bbc.com/news/articles/ckgxkg2nzpzo",
    "Higher prices could last for eight months after Iran war, minister says": "https://www.bbc.com/news/articles/cm29m98md2do",
    "Trump cancels US envoys' trip to Pakistan for talks on Iran war": "https://www.bbc.com/news/articles/c4g6nyvl29po",
    "Protest at RAF base being used in Iran conflict": "https://www.bbc.com/news/articles/c9qd8e0v309o",
    "Trump's envoys Witkoff and Kushner to fly to Pakistan for Iran talks": "https://www.bbc.com/news/articles/cy8103xklreo",
    "Who is making decisions in Iran?": "https://www.bbc.com/news/articles/cm29m732vgno",
    "US boards ship carrying Iran oil as Trump threatens mine-laying vessels": "https://www.bbc.com/news/articles/cgldw5ekrjpo",
    "Why did US and Israel attack Iran and how long could the war last?": "https://www.bbc.com/news/articles/cx2dyz6p3weo",
    "In Tehran, money is short and a return to war looms over daily life": "https://www.bbc.com/news/articles/cdrm8k7lzmko",
    "Iran says Strait of Hormuz cannot be opened due to ceasefire breaches": "https://www.bbc.com/news/articles/c3w3vqv0edpo",
    "Iran says it has seized two ships in Strait of Hormuz after vessels attacked": "https://www.bbc.com/news/articles/cdxd074kr8go",
    "US and Iran in blockade standoff as Pakistan pushes for talks": "https://www.bbc.com/news/articles/c0q9xq7knq2o",
    "Iran yet to decide if it will attend new peace talks with US, official tells BBC": "https://www.bbc.com/news/articles/c1krx8kxv23o",
    "Iran sees mass redundancies from war with US and Israel": "https://www.bbc.com/news/articles/ce84e31376zo",
    "Trump says US will not lift Hormuz blockade until deal made with Iran": "https://www.bbc.com/news/articles/cdxd88r2wjzo",
    "What we know about the Iranian ship seized by the US": "https://www.bbc.com/news/articles/c75kg0vdxyro",
    "US intercepts and seizes Iranian-flagged cargo ship, Trump says": "https://www.bbc.com/news/articles/c239500dx8ro",
    "Tehran will never cede control of Strait of Hormuz, senior Iranian politician tells BBC": "https://www.bbc.com/news/articles/cvg4jnn131qo",
    "Strait of Hormuz closed again, Iran says, as ships attacked": "https://www.bbc.com/news/articles/cx2631x6nelo",
    "What people in power think the impact of the Iran war will be": "https://www.bbc.com/news/articles/c9vl37eev7ko",
    "Iran says Strait of Hormuz is 'open' but tracking shows few ships moving": "https://www.bbc.com/news/articles/cwydexp39ddo",
    "UK and France to lead defensive mission in Strait of Hormuz": "https://www.bbc.com/news/articles/c5yjz819vmgo",
    "A moment of risk and opportunity: How two ceasefires could boost US-Iran talks": "https://www.bbc.com/news/articles/c0mjynzvw94o",
    "US lawmakers reject measure to block Trump from striking Iran": "https://www.bbc.com/news/articles/c5yve8dmvn5o",
    "Lebanon seeks peace, but Hezbollah needs to be convinced first": "https://www.bbc.com/news/articles/cr51l794mlyo",
    "Iranian footballers say Australia has given them 'hope' for safe future": "https://www.bbc.com/news/articles/c624x4xgw6xo",
    "Trump's Lebanon ceasefire takes Israel by surprise": "https://www.bbc.com/news/articles/cje4pn575jgo",
    "Lyse Doucet: Under fragile ceasefire, Iranians wonder if US deal can be done": "https://www.bbc.com/news/articles/c4g44gj7rgno",
    "How many ships are crossing the Strait of Hormuz?": "https://www.bbc.com/news/articles/c3w39lg84w2o",
    "Sri Lanka repatriates 238 Iranian sailors stranded after US torpedo attack": "https://www.bbc.com/news/articles/c9qdd318qd9o",
    "Chris Mason: Iran war has trapped Labour in a vicious circle": "https://www.bbc.com/news/articles/ce8ll6pyvdzo",
    "Trump hints Iran talks could resume this week as US port blockade continues": "https://www.bbc.com/news/articles/c20ddnz4w5lo",
    "Air show faces concern over fuel price turbulence": "https://www.bbc.com/news/articles/czx99d7yjw4o",
    "US blockade of Iran ports irresponsible and dangerous, China says": "https://www.bbc.com/news/articles/c78lleelxj4o",
    "Israelis war-weary but most oppose Iran ceasefire, poll suggests": "https://www.bbc.com/news/articles/clyxgxyeqpgo",
    "The US blockade of Iran is a gamble. Will it work?": "https://www.bbc.com/news/articles/ckgw8w7mzxgo",
    "Iran carried out highest number of executions in decades": "https://www.bbc.com/news/articles/cly9ggzy3ngo",
    "Starmer says UK will not join Trump's blockade of Iran's ports": "https://www.bbc.com/news/articles/c393wxzw4yjo",
    "Trump's blockade threat raises risks and leaves predicaments unchanged": "https://www.bbc.com/news/articles/c8dl5mly2rzo",
    "Twenty-one hours of back and forth leave US and Iran far apart": "https://www.bbc.com/news/articles/c5y7k4y0veyo",
    "After Iran talks falter, the big question is what happens next?": "https://www.bbc.com/news/articles/c5y943x2g8qo",
    "We spoke to the man making viral Lego-style AI videos for Iran. Experts say it's powerful propaganda": "https://www.bbc.com/news/articles/cjd8jrd1vnyo",
    "Concerns after satellite provider restricts Iran images following US pressure": "https://www.bbc.com/news/articles/c5y721yqe6ro",
    "JD Vance takes on a perilous mission - could it backfire?": "https://www.bbc.com/news/articles/c1d9z1q2997o",
    "Historic Vance-Ghalibaf talks must bridge deep distrust": "https://www.bbc.com/news/articles/cn9qzl12537o",
    "The five big sticking points in US-Iran talks": "https://www.bbc.com/news/articles/cx2wyn8wdz0o",
    "Ceasefire or no ceasefire, the Middle East's reshuffling is not yet done": "https://www.bbc.com/news/articles/cp3l4yk5rlgo",
    "Hot in the city: Energy crisis tests Singapore's air-con addiction": "https://www.bbc.com/news/articles/c80mxrdvkpjo",
    "Israeli strikes on Lebanon are wrong and should stop, PM says": "https://www.bbc.com/news/articles/c93enywd10ro",
    "Lebanon thought there was a ceasefire - then Israel unleashed deadly blitz": "https://www.bbc.com/news/articles/cgk0edynpmzo",
    "Israeli strikes in Lebanon 'grave violation' of ceasefire, Iran minister tells BBC": "https://www.bbc.com/news/articles/cp849k4j0y1o",
}
